# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-14 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0003_grade_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=16)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            managers=[
                ('a_m', django.db.models.manager.Manager()),
            ],
        ),
    ]
