# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-20 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
