# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-08 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_hobby',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
